-- Initial schema is maintained by Prisma. Apply with: npx prisma migrate deploy
CREATE TYPE "NewsCategory" AS ENUM ('BREAKING', 'TRANSFER', 'MATCH', 'INJURY', 'CLUB');
CREATE TYPE "ProcessingStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'PUBLISHED', 'FAILED');
CREATE TYPE "TelegramPostType" AS ENUM ('NEWS', 'MANUAL', 'LIVE_MATCH', 'PRE_MATCH', 'GOAL_ALERT', 'HALF_TIME', 'FULL_TIME');
CREATE TYPE "ManualPostStatus" AS ENUM ('DRAFT', 'SCHEDULED', 'PUBLISHED', 'CANCELLED');
CREATE TYPE "MatchStatus" AS ENUM ('SCHEDULED', 'LIVE', 'HALF_TIME', 'FINISHED', 'POSTPONED', 'CANCELLED');
CREATE TABLE "news_sources" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "rss_url" TEXT UNIQUE, "website_url" TEXT, "is_active" BOOLEAN NOT NULL DEFAULT true, "poll_interval_mins" INTEGER NOT NULL DEFAULT 10, "last_polled_at" TIMESTAMP(3), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL);
CREATE TABLE "scraped_articles" ("id" TEXT PRIMARY KEY, "source_id" TEXT NOT NULL REFERENCES "news_sources"("id") ON DELETE CASCADE, "external_id" TEXT, "url" TEXT NOT NULL UNIQUE, "headline" TEXT NOT NULL, "summary" TEXT, "featured_image" TEXT, "published_at" TIMESTAMP(3), "content_hash" TEXT NOT NULL UNIQUE, "raw_payload" JSONB, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE("source_id", "external_id"));
CREATE INDEX "scraped_articles_source_id_published_at_idx" ON "scraped_articles"("source_id", "published_at");
CREATE TABLE "processed_news" ("id" TEXT PRIMARY KEY, "article_id" TEXT NOT NULL UNIQUE REFERENCES "scraped_articles"("id") ON DELETE CASCADE, "burmese_headline" TEXT, "burmese_content" TEXT, "category" "NewsCategory", "status" "ProcessingStatus" NOT NULL DEFAULT 'PENDING', "source_attribution" TEXT, "approved_at" TIMESTAMP(3), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL);
CREATE TABLE "admin_users" ("id" TEXT PRIMARY KEY, "telegram_id" TEXT NOT NULL UNIQUE, "username" TEXT, "is_active" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL);
CREATE TABLE "manual_posts" ("id" TEXT PRIMARY KEY, "content" TEXT NOT NULL, "image_url" TEXT, "status" "ManualPostStatus" NOT NULL DEFAULT 'DRAFT', "scheduled_at" TIMESTAMP(3), "published_at" TIMESTAMP(3), "created_by_id" TEXT NOT NULL REFERENCES "admin_users"("id"), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL);
CREATE TABLE "matches" ("id" TEXT PRIMARY KEY, "provider_match_id" TEXT NOT NULL UNIQUE, "home_team" TEXT NOT NULL, "away_team" TEXT NOT NULL, "kickoff_at" TIMESTAMP(3) NOT NULL, "status" "MatchStatus" NOT NULL DEFAULT 'SCHEDULED', "is_big_match" BOOLEAN NOT NULL DEFAULT false, "live_message_id" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL);
CREATE TABLE "live_match_events" ("id" TEXT PRIMARY KEY, "match_id" TEXT NOT NULL REFERENCES "matches"("id") ON DELETE CASCADE, "provider_id" TEXT NOT NULL UNIQUE, "event_type" TEXT NOT NULL, "minute" INTEGER, "team" TEXT, "player" TEXT, "details" JSONB, "occurred_at" TIMESTAMP(3), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "telegram_posts" ("id" TEXT PRIMARY KEY, "processed_news_id" TEXT REFERENCES "processed_news"("id"), "manual_post_id" TEXT REFERENCES "manual_posts"("id"), "match_id" TEXT REFERENCES "matches"("id"), "telegram_message_id" TEXT NOT NULL UNIQUE, "channel_id" TEXT NOT NULL, "post_type" "TelegramPostType" NOT NULL, "published_at" TIMESTAMP(3) NOT NULL, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE("processed_news_id", "channel_id"));
